### ISSUE TITLE
share this project on official gitlab templates

### ISSUE THREAD

**Issue by 4383** [AntoineCezar/cookiecutter-pypkg#8]
We can generate explore [gitlab official template](https://gitlab.com/gitlab-org/project-templates) for try to generate a version of cookiecutter-pypkg compatible with these templates.

CI/CD can help you to generate this custome version without cookiecutter.
In other words we can use CI/CD/cookiecutter for generate a standalone version compatible with gitlab ecosystem and share this on the official gitlab repository. After that all gitlab users can choose our cookiecutter-pypkg directly in gitlab interface.
https://docs.gitlab.com/ee/gitlab-basics/create-project.html

**Comment by 4383** [comment]
we need to inspect how this official templates are makes

**Comment by AntoineCezar** [comment]
I like the idea, however it seems to be static files.

**Comment by 4383** [comment]
I don't know how to work gitlab template but I think it's static files but with CI we can automatize static file generation from this template easily

**Comment by 4383** [comment]
@ewjoachim do you have any ideas/suggestions about this?

**Comment by ewjoachim** [comment]
Not really, I haven't had the opportunity to work with GitLab since it introduced templates. But yes, it can be nice to only do the work once.

As a side note, as much as I like bootstrapping tools, I prefer having the opportunity to review every file before it's commited on the repo, so that I don't get too much boilerplate cargo cult files. My ideal template would include some doc explaining all the "specific files" of the project, and how they work, for both the person using cookiecutter/..., and the future devs of the repo. The advantage of cookie cutter in this case is that one may get rid of useless file from the beginning.

**Comment by AntoineCezar** [comment]
I think gitlab integration is not feasable. If someone want gitlab template it can generate a static one from the cookiecutter one
